### ISSUE TITLE
CommandNotFound Error

### ISSUE THREAD

**Issue by OneParsec** [nk412/pyfzf#8]
raise CommandNotFound(progname, list(cls.env.path))
plumbum.commands.processes.CommandNotFound: ('sh', [<LocalPath C:\Program Files (x86)\Common Files\Oracle\Java\javapath>, <LocalPath C:\Program Files (x86)\VMware\VMware Workstation\bin>, <LocalPath C:\Windows\system32>, <LocalPath C:\Windows>, <LocalPath C:\Windows\System32\Wbem>, <LocalPath C:\Windows\System32\WindowsPowerShell\v1.0>, <LocalPath C:\Windows\System32\OpenSSH>, <LocalPath C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common>, <LocalPath C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR>, <LocalPath C:\Program Files\PuTTY>, <LocalPath C:\Program Files\Git\cmd>, <LocalPath C:\ProgramData\chocolatey\bin>, <LocalPath .>, <LocalPath C:\Program Files (x86)\GNU\GnuPG\pub>, <LocalPath C:\Program Files\dotnet>, <LocalPath C:\Ruby30-x64\bin>, <LocalPath C:\Users\Alexandr\scoop\shims>, <LocalPath C:\Users\Alexandr\AppData\Local\Programs\Python\Python39\Scripts>, <LocalPath C:\Users\Alexandr\AppData\Local\Programs\Python\Python39>, <LocalPath C:\Users\Alexandr\AppData\Local\Microsoft\WindowsApps>, <LocalPath C:\Program Files (x86)\Nmap>, <LocalPath C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.1\bin>, <LocalPath .>, <LocalPath C:\Program Files\CMake\bin>, <LocalPath C:\Users\Alexandr\.dotnet\tools>, <LocalPath C:\Users\Alexandr\AppData\Local\Programs\VSCodium\bin>])

I installed plumbum, fzf with choco

**Comment by nk412** [comment]
Ah yeah, this wasn't intended to run on Windows. I'll try to patch this to remove the dependency on plumbum.
PRs welcome. Thanks for flagging :)

**Comment by addy3494** [comment]
Hi @nk412  - Any luck on implementing this ? ill try to cut a feature incase its not started.
badly need this in windows

**Comment by nk412** [comment]
Haven't had a chance to look at this yet! Please feel free to contribute, @addy3494.
All that's needed is removing the `plumbum` dependency and directly call out `fzf`.
I can have a look at this in a week if you can't.

**Comment by brookite** [comment]
This issue can be closed. It has been fixed in 0.3.0

**Comment by nk412** [comment]
Thanks @brookite
